### PR TITLE
Allow type whitelist

### PR DESCRIPTION
**Pull request by mcchrish**
This is to allow some types. For example I don't want images to be removed.

### CODE REVIEW

**Comment by wooorm** [comment]
Hi! Thanks for working on this.

Could you first provide some more info? Why is this needed? What does this solve? I’m also missing docs for this feature.
Finally: Why would you want to ignore `image`, but not `imageReference`?

**Comment by mcchrish** [comment]
I need this so that I can parse down a markdown without links but still allow images. We need images in our current project but we don't want our users to be able to include links whatsoever that redirects them to other pages instead of just loading our own parsed markdown. Essentially we just want basic content.

I'm not quite sure about what `imageReference` are so I opt to still not include them.

If you approve this use case, I'll add some docs.

**Comment by wooorm** [comment]
[Image references](https://github.com/syntax-tree/mdast#imagereference) are another way to create images.

And what would you suggest should happen with [definitions](https://github.com/syntax-tree/mdast#definition)? We currently strip them because all references are removed, but if some references remain, it gets trickier.

**Comment by wooorm** [comment]
What I’m getting it is that you probably do want to remove image references as well.

I’m wondering if we can solve your problem in a way that is useful to other people. But it’s also a [small plugin](https://github.com/remarkjs/remark-unlink/blob/master/index.js) so you can also create your own that only strips links.

**Comment by mcchrish** [comment]
Thanks for the input @wooorm. Decided to use our own plugin instead.
Closing this PR.

**Pull request closed without merging**
